### ISSUE TITLE
Tidak bisa ngetik di browser hp (Android)

### ISSUE THREAD

**Issue by axmad386** [hibrizii/ngetik-ngebut#1]
Entah bug atau bukan, tp saat klik start keyboard hp gk muncul. Jadi gk bisa ngetik. Mungkin ada yang kurang di accessibilitynya. Cmiiw

**Comment by hibrizii** [comment]
memang ini khusus buat pc bang. tp scr teknis karena gk ada elemen input focused, jadinya keyboardnya gk muncul

**Comment by axmad386** [comment]
oh I see, saya coba di PC aman si. Mantab
